<?php

namespace Database\Seeders;

use App\Helpers\Helpers;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        DB::table('categories')->insert(
//            [
//                [
//                    'id' => 1,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'rank' => 0,
//                    'title' => 'Liên kết nhanh',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 3,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 1,
//                    'rank' => 0,
//                    'title' => '33win1',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 4,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 1,
//                    'rank' => 1,
//                    'title' => '33win2',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 5,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 1,
//                    'rank' => 2,
//                    'title' => '33win3',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 6,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 1,
//                    'rank' => 3,
//                    'title' => '33win4',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 7,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 1,
//                    'rank' => 4,
//                    'title' => '33win5',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 8,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 1,
//                    'rank' => 5,
//                    'title' => '33win6',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 2,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'rank' => 1,
//                    'title' => 'Tổng hợp',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 9,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 2,
//                    'rank' => 0,
//                    'title' => '33win1',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 10,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 2,
//                    'rank' => 1,
//                    'title' => '33win2',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 11,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 2,
//                    'rank' => 2,
//                    'title' => '33win3',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 12,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 2,
//                    'rank' => 3,
//                    'title' => '33win4',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 13,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 2,
//                    'rank' => 4,
//                    'title' => '33win5',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//                [
//                    'id' => 14,
//                    'uuid' => Helpers::buildUUID(),
//                    'user_id' => 1,
//                    'parent_id' => 2,
//                    'rank' => 5,
//                    'title' => '33win6',
//                    'redirect_url' => '#',
//                    'type' => \dataCategory::TYPE[0],
//                    'status' => \dataCategory::ACTIVE,
//                    'created_at' => date("Y/m/d H:i:s"),
//                    'updated_at' => date("Y/m/d H:i:s"),
//                ],
//            ]
//        );
    }
}
