version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php8.1/33win99Org/Dockerfile
        container_name: 33win99_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - app_storage:/var/www/html/storage
        ports:
            - "8085:80"
        networks:
            - 33win_backend

networks:
    33win_backend:
        external: true

volumes:
    app_storage:
