version: '3.8'

services:
    db:
        image: mysql:5.7
        container_name: 33win_db
        environment:
            MYSQL_ROOT_PASSWORD: Idsa32ADsaWsdawW
            MYSQL_DATABASE: 33win_2
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - 33win_backend

networks:
    33win_backend:
        external: true

volumes:
    db_data:
